name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # adjust this if your default branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Updated from v2 to v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated from v2 to v3
      with:
        node-version: '16'  # Updated to a more recent version
    
    - name: Install dependencies
      run: |
        npm install dotenv
        npm install  # or 'npm ci' if you have a package-lock.json
    
    - name: Build
      run: |
        echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" > .env
        node build.js
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4  # Updated to v4
      with:
        branch: gh-pages
        folder: dist
